### ISSUE TITLE
Add support for web browsers with JavaScript disabled

### ISSUE THREAD

**Issue by grizzlyuser** [ProtonMail/WebClients#125]
Some users prefer to disable JavaScript in their web browsers for different reasons, like for:
* security (to protect from yet unpublished vulnerabilities like recent Spectre & Meltdown,  [Rowhammer](https://github.com/IAIK/rowhammerjs) or the like)
* privacy
* saving system performance and battery life
* improving site loading times on slow connections or reducing traffic usage (simple loading of ProtonMail login page downloads >1MB of stuff).
* not running untrusted proprietary minimized obfuscated JS code of which the Web is full nowadays (not an issue of PM basically, but there is a ticket #37 for LibreJS support)
* etc.

It would be great to make web-version of ProtonMail to work with no client-side JS, so that those users can still use it without the need to specially enable JS for it. 
Some users may not even know the web-client is free / libre / open-source, and without that knowledge they'll just go away on their first visit when they see it doesn't work without JS.

Just look at GitHub, Gmail (basic HTML version), Google Search, Amazon - their basic functionality can work with no JS. Some things may be broken or look different, though, but they are mostly minor.

Please correct me if I'm wrong, but some modern JS frameworks can work with **server-side rendering**. For example: Angular, React, and it seems there are [solution(s) for AngularJS](https://stackoverflow.com/questions/16232631/angularjs-server-side-rendering).

A separate lightweight fallback on pure HTML & CSS can be an alternative solution.

**Comment by nagromc** [comment]
> some modern JS frameworks can work with **server-side** rendering

This would break end-to-end encryption, the **core** feature of ProtonMail. To keep privacy and secrecy, you need to trust **no one**, and to do the OpenPGP job on the client side. It's the very fundamental concept of E2EE.

Please correct me if I'm wrong (I'm not an expert), but I think it's not possible to implement OpenPGP as pure HTML, since it is just a static description language. I believe you need JS to do the (complex) OpenPGP tasks. And even you could do the visual rendering on server side, you would still need JS client side for OpenPGP.

I understand the reasons listed above, but I would **not** sacrifice E2EE over them.

**Comment by kontrollanten** [comment]
One first step could be to use something like [react-snap](https://github.com/stereobooster/react-snap) to just pre-render the login page. If the JS in the login page is loaded async that would decrease the initial download size from 2,2 mb to 200-300 kb. So the JS files would be downloaded while the user types his password.

**Comment by grizzlyuser** [comment]
Being quite new PM user, I only now realized how does it work with encryption. I watched requests sent to PM server during navigation in Inbox, and message bodies (but not subjects) in their responses indeed are PGP encrypted, so they seem to be decrypted only on client side. @nagromc, thanks to pointing me into the right direction!

So if there must be something that decrypts those contents on the client side anyway, than what about requiring JS code only for that functionality?

For example, what about this solution? The server could return pre-rendered webpage, where all the end-to-end OpenPGP encrypted content (like message bodies and whatever else) is rendered in place of the actual content. The lightweight crypto code would then scan the page and detect those contents by message headers ( like `-----BEGIN PGP MESSAGE-----`, `-----END PGP MESSAGE-----`), decrypt them and replace with the decrypted content. Sent messages can still be e2e encrypted by the crypto code.

As I see it, it can reduce the amount of client code required to accomplish the most essential tasks. This can benefit the end users by:
* letting the security-conscious users to more easily review the code that runs on their machine
* letting somebody who wants that, to run the code locally more easily by reducing building time. For example, the code can be incapsulated into a [WebExtension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions), or added as a user script to [Greasemonkey](https://en.wikipedia.org/wiki/Greasemonkey).
* reducing the usage of CPU. This can be a major benefit for Tor Browser users, who chose "Safer" or "Safest" option in TBB Security Settings. Those options [disable optimizations of JavaScript engine](https://www.torproject.org/projects/torbrowser/design/#other-security), like [JIT](https://en.wikipedia.org/wiki/Just-in-time_compilation). I've just tried to log into PM with the slider in "Safer" position. It took more than a minute to display the Inbox after a hit on a LOGIN button. During that time, TBB constantly utilized a single core of i7 8850H CPU.
* probably reducing the usage of traffic as well. For example, AFAIK, Tor Browser clears cache/cookies/history/etc. each time it's closed or "New Identity" is selected by the user. So the users will need to download all the code for web client each time.

**Comment by grizzlyuser** [comment]
> letting somebody who wants that, to run the code locally more easily by reducing building time. For example, the code can be incapsulated into a WebExtension, or added as a user script to Greasemonkey.

Moreover, there is a [Mailvelope](https://www.mailvelope.com/) web browser extension, and it seems to do right what is needed. And the project has a mailvelope/mailvelope#550 for PM support. It would be great to see mutual support of both projects, and that would help to resolve the current issue.

**Comment by ArcanisCz** [comment]
> Please correct me if I'm wrong, but some modern JS frameworks can work with **server-side rendering**.

Having prerendered first screen on server using SSR for React/angular/etc doesnt solve javascript payload. JS files will be downloaded anyway, but first **visible** ui will be delivered faster. First meaningful user interaction would still wait for js files to download. SSR solves mainly UX problem of not-showing loaders to user. (And SEO problems)

SPAs are developed with premise that first application load will be slower, but subsequent visits will have js files cached. In a long term, they will save bandwitch by exchanging only data with server (through ajax), instead of sending full repeating html markup each request from server.

But if caching is not thing in Tor (and there are some security js de-optimizations as you mentioned), this premise doesnt work, so full server application would probably save bandwitch and CPU usage (but will use more server usage instead of client usage). But it would need totally different infrastructure and code. And Protonmail is probably not willing to maintain 2 separate applications just for this.
