### ISSUE TITLE
Fix links to localhost version when running the dev version

### ISSUE THREAD

**Issue by anooprh** [ProtonMail/WebClients#15]
* Desktop
* Chrome
* Linux
* /login
* Free?

### Description or steps to reproduce the problem

When I run the development version of Web Client and the home page opens up at http://localhost:8080/login , all the other links point to protonmail.com instead of localhost. For eg https://protonmail.com/signup

### Expected Behavior
The web client should be self sufficient to run on a localhost with not external dependencies. 

### Actual Behavior
All links are pointed to protonmail.com TLD

**Comment by Super-Baleine** [comment]
Hey,
If you're on Linux, while you're testing the webapp on localhost, you can go on /etc/hosts and add : 
**127.0.0.1        protonmail.com**
Think to comment "#" this line after having tested, because you will not be able to go on their production version... :sweat_smile: 

I precise that it's just a client, that's why I think the "dependencies" are totally normal... x)

**Comment by bartbutler** [comment]
So, looking at the links on the login page we have 'Back to protonmail.com', which is obvious, we have the release notes, which are hosted are our blog, also totally normal, and some links inside the help modal to our support portal, which is on protonmail.com. All of these are separate from the web app, thus the links aren't self-referencing. The only strange one is the signup link, which takes you to protonmail.com because the signup flow starts there for SEO reasons. It's a little strange I admin, but it's not a bug. If you want to create an account from the local instance, navigate directly to /create/new.
