### ISSUE TITLE
UX ideas from Hey.com

### ISSUE THREAD

**Issue by teampolyglot** [ProtonMail/WebClients#190]
There are some good UI/UX ideas in Hey.com: [Features](https://hey.com/features/) , [How it works](https://hey.com/how-it-works/)

- New senders must be whitelisted via The Screener
- Reply Later and Set Aside queues.
- Feed view
- and more

Are there plans to bring any of these to ProtonMail's web interface?

**Comment by cmolina** [comment]
Hi @eshnil ! I also want to have this use case covered. Do you have a workaround so far?

Yesterday I wrote [a blog post](https://cmolina.dev/posts/2021/05/migrating-from-hey/) for a set of folders, contact groups and filter to mimic the Hey screening feature. It works pretty well for me so far.

I am posting here because there is a limitation regarding the maximum amount of contacts a contact group can include, which will force me to keep renaming and changing the contact group. I wanted to know if the ProtonMail team has ideas on how to implement these concepts.
