### ISSUE TITLE
Implement support for U2F / FIDO2 as second login factor

### ISSUE THREAD

**Issue by RAYs3T** [ProtonMail/WebClients#197]
**Is your feature request related to a problem? Please describe.**
The login to such an important resource should be secured as best as possible.

**Describe the solution you'd like**
When authentificating with a password, you should have the option to specify a U2F / FIDO2 device as second factor. Not only a time based code generator.

Also it would be nice if you could set-up multiples devices.

**Describe alternatives you've considered**
There are non. You have to use timed based codes...

**Additional context**
Requires major changes to the server side auth mechanism.

**Comment by bartbutler** [comment]
Hi. We agree, but due to restrictions in FIDO/U2F (and WebAuthn) each registration is limited to a single domain, which presents problems for us as we currently use two (protonmail.com and protonvpn.com). We will be consolidating our domains in the coming months and then revisit this--we did do much of the work to implement U2F on the server side already.

**Comment by ddimick** [comment]
Please re-open this issue, as the domain consolidation has now taken place.

**Comment by bartbutler** [comment]
Yup.

**Comment by amund-ersland** [comment]
I get errors trying to use my yubikey in safari and firefox on mac os. It works fine in ios

**Comment by RAYs3T** [comment]
@amund-ersland You're not talking about FIDO here...? Since this is not yet supported :(

**Comment by bartbutler** [comment]
It is supported for a month or two now (on web).
