### ISSUE TITLE
ProtonMail can't handle ed25519 DKIM signatures

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#226]
Any email which is signed with ed25519 DKIM signatures will be delivered directly to the spam folder which is pretty absurd. 

@bartbutler

**Comment by bartbutler** [comment]
Agreed, we'll look into this.

**Comment by ghost** [comment]
Here are some extracts from incoming message header: 

Authentication-Results: mailinxxx.protonmail.ch; **dkim=permerror** (0-bit key)
Dkim-Signature: v=1; a=**ed25519-sha256**; c=relaxed/simple;

Custom domains hosted at ProtonMail should use ed25519-sha256 signing algorithm instead of RSA. 
Because the previous DKIM RSA record was too long and needed to break it into multiple lines, ProtonMail come up with the `CNAME` record solution with the similar values for custom domains as the following: **protonmail.domainkey.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.domains.proton.ch.**

However, with the **ed25519-sha256** signing algorithm the `TXT` record would be this long: 
`selector._domainkey.domain IN TXT "v=DKIM1; k=ed25519;  p=11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo="`

Significantly faster, and smaller, and so it is recommended for DNS. 
Regarding the ed25519-sha256 signing algorithm, see RFC 8463: https://tools.ietf.org/html/rfc8463

**Comment by justatemporaluser** [comment]
One more thing I should add to this. 

Custom domains hosted at ProtonMail should use ed25519-sha256 signing algorithm instead of RSA. 
Because the DKIM RSA record was too long and needed to break it into multiple lines, ProtonMail come up with the `CNAME` records with the following values for custom domains: **protonmail.domainkey.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.domains.proton.ch.**

However, with the **ed25519-sha256** signing algorithm the `TXT` record would be this long: 
`selector._domainkey.domain IN TXT "v=DKIM1; k=ed25519;  p=11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo="`

Significantly faster and smaller, and so it is recommended for DNS.

**Comment by bartbutler** [comment]
The CNAME system is actually so we can handle key rotation automatically on behalf of our customers, not for length reasons.

**Comment by ghost** [comment]
Yes, I forgot that. However, the previous system was a disaster because the RSA record was way too long, and it was not broken into multiple lines which prevented the DNS zone to be signed with DNSSEC. 

Anyway, ProtonMail should not throw the ed25519-sha256 signed email to spam. (dkim=permerror)

**Comment by glroman** [comment]
And...what is the status here?  Does PM support inbound or outbound emails with DKIM Ed25519-signatures?  Or are we still in RSA land?
