### ISSUE TITLE
Issues on Protonmail by Sifudu Peter

### ISSUE THREAD

**Issue by Sifudu** [ProtonMail/WebClients#232]
Why resetting the password makes the user lose all his or her emails...  The system should be worked on such that the user does not lose the emails because thus there should be a mechanism of resetting usernames and passwords while not affecting the  content in the inbox and sent items
 Protonmail should be re engineered in such a way that the user can send and receive emails from other email accounts like google mail, hotmails, yahoo etc instead of just from another user of another protonmail account.
The dashboard should be re worked on to include a summary of the number of new items in the inbox

**Comment by bartbutler** [comment]
The password encrypts the emails via a keychain. If you lose the password, you lose access to the keychain and your email content. We are working on schemes to facilitate data recovery more easily (you can already do it if you remember your old password) but encryption is core to what Proton is and does.

We can send and receive emails from other services and have since the beginning, there is no restriction that emails can only be sent to other ProtonMail users.
