### ISSUE TITLE
[FEATURE REQUEST] Scheduled Email Sending

### ISSUE THREAD

**Issue by darigovresearch** [ProtonMail/WebClients#240]
**Is your feature request related to a problem? Please describe.**
Other email applications allow you to set a time for the email to be sent from your mail box, for example at 8am or a specific time chosen by the user.

**Describe the solution you'd like**
A button when composing an email to open a modal to select the date and time to be sent. Email could then be stored in a "Scheduled send" folder or just in the outbox with a timer badge/icon

**Describe alternatives you've considered**
Could be in a selector or a dropdown but think the above solution would be the best implementation.

**Additional context**
Feature request was also created for the android app, wanted to mention it here as it would also be helpful to do in the web app as well

https://github.com/ProtonMail/proton-mail-android/issues/18

**Comment by erikeah** [comment]
I would like to add that is a feature request for a long time, for 5 years ago. As professional I really need it, sometimes to ensure that your mail will be read you need to send it in a specific hour of the day.

Please prior this, I love protonmail and I have recommended to friends and they have to switch back to other services because this feature is very valuable when you know how to use it.

[LINK TO USERVOICE REQUEST](https://protonmail.uservoice.com/forums/284483-protonmail/suggestions/7158412-schedule-emails-in-advance)

**Comment by darigovresearch** [comment]
@mmso can you advise why this issue was closed?

**Comment by mmso** [comment]
This issue was closed as part of the migration to the new React codebase and mono-repository for Proton webapps. For future requests, you are welcome to submit them to https://protonmail.uservoice.com/forums/284483-protonmail. Scheduled email sending will be coming shortly however.
