### ISSUE TITLE
Stop deleting inactive accounts!

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#275]
You had over 1126 votes already. The management of the company simply doesn't care. They just don't care about their users. Go to hell, you moron who invented account deletion! You don't belong at Proton! I've never seen such a fucked up idea anywhere else. Dear developers, please fuck this bastard once and then kick him out of the company. Deleting accounts will do NOTHING good. And your greed will only lead to more negative! You just read that thread already.

https://protonmail.uservoice.com/forums/284483-protonmail/suggestions/45017578-do-not-delete-inactive-accounts

Stop deleting our accounts!!! Stop being mad!!! Stop the fuking stupid management!!!

Stop writing stupid excuses!!! Stop writing stupid boilerplate answers!!! Just fire the fuck out of that employee who came up with that!!! You get so much negativity written about it everywhere, but you just don't give a fuck!

Just don't answer me with your idiotic "We understand your concern..."! Everyone knows your fucking mantra by heart. Just fuck off with the account deletion feature!!!

**Comment by itsnotsaved** [comment]
Well, i thought to suggest a solution that may comfortable for both sides (proton and users/customers) and i know proton doesn't like to keep accounts forever for many reasons. Also, account & data deletion is necessary for privacy friendly provider.

1. Provide your (proton) **most preferred inactive account deletion period** as default (e.g. 6 months or else); you don't have to change your mind about that decision.
2. Provide a new setting in account settings (e.g. deletion area) for users to customize account deletion period. (e.g. 1 month, 3 months, 6 months, 1 year, 2 year, 3 year, 4 year). Keep proton preferred deletion period as default. 
(If really necessary, may be you can keep this setting locked e.g. 1 week for new users)
3. Check top providers **active (not proposed)** inactive account deletion policy (e.g. gmail and etc) and take it into consideration. Otherwise if proton delete inactive accounts within short period of time then we have to find and use privacy-risk providers that offer long period.
4. Review proton community, user base concerns, requests, and unavoidable situations **(e.g. normal or serious ills, natural or unnatural disasters, other effective possibilities to normal life)** and provide a max period (e.g. 3 year) in auto-deletion setting for necessary users to customize. (e.g. many people use their accounts for various important things)

Also, i expect atleast 3 years period.

**Comment by Linerly** [comment]
AFAIK, Google's inactive account deletion period is 2 years

**Comment by bartbutler** [comment]
To be clear, we don't currently and have never (to my knowledge) deleted *any* accounts for inactivity. However, reserving the right to do so is important, because we need the flexibility to be able to serve the people who actually use Proton services rather than store data for eternity for people who do not. There are also lots of throwaway and other defunct accounts, potentially with weak passwords, which represent an ongoing spam and abuse threat were they to be hacked.

This does not mean that accounts are or will be automatically deleted exactly at the 1-year mark or automatically deleted at all, but some policy needs to be in place to set appropriate expectations for users, and well in advance. We will certainly be engaging with users and considering user input on this policy and others.

Given that we actually aren't deleting any accounts, and that this isn't a technical or product issue, I'm closing this.
