### ISSUE TITLE
Self-email with pm.me domain shows up twice

### ISSUE THREAD

**Issue by 0joshuaolson1** [ProtonMail/WebClients#87]
On Chrome 67 (Debian Linux 64 bit), only when I send an email to myself with a `pm.me` domain (with either my actual email name/'part', or an alias like with an extra dot), two emails show up (combined with a `(2)`).

**Comment by EpokK** [comment]
This will happen if you receive a message to 2 aliases (`toto@pm.me` and `toto@protonmail.com`), but also if you send yourself a message from one alias to another.

`toto@protonmail.com` > `toto@pm.me` will have 1 sent and 1 received.

**Comment by 0joshuaolson1** [comment]
Why does the sent mail show up separately in my inbox though? I didn't hear of a correction.

**Comment by bartbutler** [comment]
That should be one email unless the sender and recipient are different addresses. Could you post the headers here?

**Comment by 0joshuaolson1** [comment]
First email's header:
```
X-Pm-Origin: internal
X-Pm-Content-Encryption: end-to-end
Subject: apt
From: 0joshuaolson1 <0joshuaolson1@protonmail.com>
Date: Sat, 28 Jul 2018 19:19:55 +0000
Mime-Version: 1.0
Content-Type: text/plain
To: 0joshuaolson1@pm.me <0joshuaolson1@pm.me>
Message-Id: <vtzPmNW1KzqVpD8b3zukv3Y52hKiqDEVBBG-wL5XLYqyYUe_F6Bsbketyxdlp9A0ZMfWB_f5suDGld4kbol6p5j0hKzqxbhUkavKOpx5XiM=@protonmail.com>
X-Pm-Recipient-Authentication: 0joshuaolson1%40pm.me=pgp-pm
X-Pm-Recipient-Encryption: 0joshuaolson1%40pm.me=pgp-pm-pinned


-----BEGIN PGP MESSAGE-----
Version: ProtonMail
Comment: https://protonmail.com

wcBMAxujguaL8lyAAQf/VLWZcofogfRm2wPFv47C33/ZCqD6/Cx5/LXJTqir
F6iCkdBn78Pr2UVHApIqNzAUlrXy/4+fDxJIy+0k9KrwoN7gtUDiVi2atH+u
jkDfvv6XrOVxX+HPxPunkc+iWZQ/DH4d8RN2P3piCXg/c2/kwBcFfbBNvqiA
kUbzCx0bajy9bD8+XiIebqs53jypoSg9Cn8MZixQbmPxG/YQ3kSQ11RL2s81
BbjmOez4BvH5B5sJ3cJbsn5j5KCZJ2PCtp9R0FJOIhX/YKUT5NH2ZL2gDRyv
Ho2D1TMmEzoSBXoaNOltOWLfGYzusg31zeIqDiltnflpP8ZfAi+BIBh9skHG
TNLBqgE3JAfHfzNGGXCLcqVexDmPjeYX3Eg1y9+no7hVvF10mrL7SG8TeiwL
D32emgAgsdl7cBbNjdABGqW+YaFWkCz3Go0HwZAfyCC3NM9npHE1qrlfGAWc
s0CCvmWOlCvvnAtaq3ilMqElDm3wWH+o+mpSjQi1ja585ycnQw2p63fCpsyM
tSwBPE13ejyg8uz+vSPUHgHBqP9fUnk7Pf1LaXYckzRaVG5zz2DPQ7R5vRyU
/3e0RLKM4ATWOWEawbwANz/X/62g3X/lGDZw04g0xfjiTUVAeLUs7A7qH7ju
3FZ7tMr9nPbSKif3ZwhPVHsJfTOF/2TQgHyXw/QsIwsUrfILUFFSiR+rMOHa
tNLkZwvOqk56+YH7IMDbFZpC1ffhP/XScJzZCwXxzWN4BfOpV2cozYMz39sn
k5Ns/WRSwvt5DWVAt62sbYTcFAchuxKCLurMibXMRvDxJUG4+A3sgHE2hPM0
s13HronpRhu2ylO1lCYPwsS8w10gbrtzCMR3nBJCkHEoBH+ZpJO89gYUeso9
YqrEXFP1NCaW2JzZg6mpAUZSiRR4KNi+kDGaopHuRamXijY0snOtK+WDCY70
OjxJEzVqPWRw94y6qjZFhdedgKk5hyMpMIxlGUUfxdRcXxYF1Qvg6N8lnAnO
AlAJX1rFG6c0KqS0UOd/6U4KUp4MqcPSN/wgOaBHkr20+4ID2WQTBhlDHQrq
EIAdtWumlEYKuEBtOT9lfQV+U8c2l7tx/ND79NCHl6OPGYuyYi9Xs4i2kwvp
1og8tlaz/7cKvmPdkMP0YjuL/pFGx0/F7XLdEW7jRCEv/B9TsA==
=AMJ5
-----END PGP MESSAGE-----
```
Second email's header:
```
X-Pm-Origin: internal
X-Pm-Content-Encryption: end-to-end
Subject: apt
From: 0joshuaolson1 <0joshuaolson1@protonmail.com>
Date: Sat, 28 Jul 2018 15:19:55 -0400
Mime-Version: 1.0
Content-Type: text/plain
To: 0joshuaolson1@pm.me <0joshuaolson1@pm.me>
Message-Id: <vtzPmNW1KzqVpD8b3zukv3Y52hKiqDEVBBG-wL5XLYqyYUe_F6Bsbketyxdlp9A0ZMfWB_f5suDGld4kbol6p5j0hKzqxbhUkavKOpx5XiM=@protonmail.com>
X-Original-To: 0joshuaolson1@pm.me
Return-Path: <0joshuaolson1@protonmail.com>
Delivered-To: 0joshuaolson1@pm.me
Received: from mail.protonmail.ch by mail.protonmail.ch; Sat, 28 Jul 2018 15:19:55 -0400


-----BEGIN PGP MESSAGE-----
Version: ProtonMail
Comment: https://protonmail.com

wcBMA2aRlK0pj1DPAQf+Jb+/AzJsDkiTccgAO4TkVQve5iQTbvjj7DN8LRAT
lKVcs4IvAg6UjzDVBmZ+ziJjqJuZygymKVzO1lI7nFWTd2xDsIQhJzK81RhY
wP7fz3c86iLDrJViuUlIOo4RX3asKIix7HHT24oGQeWi2cu5wdk3SyU/Nbql
BAhZEpdL8XZl5smikX4AKG5202QdZbIaOUK2EGIl+5cdBwq6qu5GOZLjYk6e
bcPwv5aZahksr0WbwRHZFaSEBMV8Fo+QutSm8rWfVAhIaWM/Xlm+wFDi30th
tZ1unfwLJ0LttvR5CjgyHmmnVPKyRsABOsrNR4sxn5rOtmoeeGFfluazFzqN
5tLBqgE3JAfHfzNGGXCLcqVexDmPjeYX3Eg1y9+no7hVvF10mrL7SG8TeiwL
D32emgAgsdl7cBbNjdABGqW+YaFWkCz3Go0HwZAfyCC3NM9npHE1qrlfGAWc
s0CCvmWOlCvvnAtaq3ilMqElDm3wWH+o+mpSjQi1ja585ycnQw2p63fCpsyM
tSwBPE13ejyg8uz+vSPUHgHBqP9fUnk7Pf1LaXYckzRaVG5zz2DPQ7R5vRyU
/3e0RLKM4ATWOWEawbwANz/X/62g3X/lGDZw04g0xfjiTUVAeLUs7A7qH7ju
3FZ7tMr9nPbSKif3ZwhPVHsJfTOF/2TQgHyXw/QsIwsUrfILUFFSiR+rMOHa
tNLkZwvOqk56+YH7IMDbFZpC1ffhP/XScJzZCwXxzWN4BfOpV2cozYMz39sn
k5Ns/WRSwvt5DWVAt62sbYTcFAchuxKCLurMibXMRvDxJUG4+A3sgHE2hPM0
s13HronpRhu2ylO1lCYPwsS8w10gbrtzCMR3nBJCkHEoBH+ZpJO89gYUeso9
YqrEXFP1NCaW2JzZg6mpAUZSiRR4KNi+kDGaopHuRamXijY0snOtK+WDCY70
OjxJEzVqPWRw94y6qjZFhdedgKk5hyMpMIxlGUUfxdRcXxYF1Qvg6N8lnAnO
AlAJX1rFG6c0KqS0UOd/6U4KUp4MqcPSN/wgOaBHkr20+4ID2WQTBhlDHQrq
EIAdtWumlEYKuEBtOT9lfQV+U8c2l7tx/ND79NCHl6OPGYuyYi9Xs4i2kwvp
1og8tlaz/7cKvmPdkMP0YjuL/pFGx0/F7XLdEW7jRCEv/B9TsA==
=aw1X
-----END PGP MESSAGE-----
```
The second one has the forwarding headers. The two pgp messages are different except in the middle.

**Comment by bartbutler** [comment]
So you sent a message from your protonmail.com address to your pm.me address. So it's not a self-email, as the two messages are encrypted with entirely different keypairs (this is for privacy, and while it's trivial here, outside observers should not be able to determine that two email addresses belong to the same user by comparing keys). The first email is the sent message, belonging to the protonmail.com address. The second is the received email, belonging to the pm.me address. 

If you send a message from your protonmail.com address to your protonmail.com address you will have one message which is both sent and received, but that's not what you did here.

**Comment by 0joshuaolson1** [comment]
Both domains/addresses refer to the same inbox: mine. I didn't send it twice. Why is this difficult to understand?

**Comment by bartbutler** [comment]
It is understood, and it is intended. The logic goes like this. You are a
user, you have one or more addresses, each of which owns a collection of
messages. In terms of mail delivery, addresses are treated independently.
They each have their own set of keys and messages are encrypted with the
keys of a specific address.

You send from address A to address A, we only have one copy, because there
is no point in duplicate copies for the same address. You send from address
A to address B, the sender A has a copy and the recipient B has a copy,
encrypted with their respective keys.

You are arguing that because A and B are both owned by you, and because you
inbox view is merged, you should only get one copy. This is certainly
doable, but logically a problem, because not everyone uses a merged inbox.
With Bridge, for instance, addresses can be viewed separately and there
what you suggest would result in either apparent non-delivery or a missing
sent message.

If I had a business and had two addresses, sales and accounting, and sent a
message from one to the other, that message belongs to both addresses, and
if I exported either address separately I would expect that message to be
in the dump.

So to be logically consistent we do not consider messages between two
separate addresses to be a self-delivery eligible for deduplication in this
way.

**Comment by 0joshuaolson1** [comment]
I see, thanks. I would expect that a view of only ***@protonmail.com's inbox wouldn't have the received email. That's still consistent?

**Comment by bartbutler** [comment]
Correct.

**Comment by 0joshuaolson1** [comment]
Wouldn't that solve
> With Bridge, for instance, addresses can be viewed separately and there what you suggest would result in either apparent non-delivery or a missing sent message.

**Comment by bartbutler** [comment]
Not sure I follow. If you viewed the addresses separately, the protonmail.com address would have the sent message, and the pm.me address would have the received message. That's why when you view the addresses merged, you have two copies, one sent, one received.

**Comment by 0joshuaolson1** [comment]
The perceived bug is that two emails are displayed in the *inbox*.

**Comment by 0joshuaolson1** [comment]
I propose that emails in this case would only appear once in an inbox:
- combined view, like the basic inbox
- only the `pm.me` inbox, if using Bridge

Does that make sense?

**Comment by bartbutler** [comment]
There are two copies--hiding one for certain views won't work, because then you can't delete or organize the hidden one.

Now, when you say inbox, you mean you see both messages when you open the conversation, right? and it has (2) next to it. If you switch to message mode, you'll only see one message in the inbox because the other lives in the sent folder. If both messages were actually in the inbox folder itself that would be a bug.

**Comment by 0joshuaolson1** [comment]
I don't see any bug in message mode (reader FYI: disabled conversation grouping).

I managed to delete one of the `(2)` as a workaround (or I can just send to my longer address), so I'm not too bothered by this WONTFIX.
